# Docker Compose para el Sistema de Control de Gastos del Hogar
# Configuración completa con PostgreSQL y volúmenes persistentes

version: '3.8'

services:
  # Aplicación principal
  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_TYPE=postgresql
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=expense_tracker
      - POSTGRES_USER=expense_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_SSL=false
      - JWT_SECRET=super-secret-jwt-key-change-in-production
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - app_data:/app/data
      - app_logs:/app/server/logs
    restart: unless-stopped
    networks:
      - expense_network

  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=expense_tracker
      - POSTGRES_USER=expense_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - expense_network

  # Aplicación con SQLite (alternativa)
  app-sqlite:
    build: .
    ports:
      - "3001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_TYPE=sqlite
      - SQLITE_DB_PATH=/app/data/database.sqlite
      - JWT_SECRET=super-secret-jwt-key-change-in-production
    volumes:
      - sqlite_data:/app/data
      - app_logs_sqlite:/app/server/logs
    restart: unless-stopped
    profiles:
      - sqlite
    networks:
      - expense_network

volumes:
  postgres_data:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local
  sqlite_data:
    driver: local
  app_logs_sqlite:
    driver: local

networks:
  expense_network:
    driver: bridge
